name: Illyrian's CI/CD
run-name: "Illyrian's CI/CD"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: setup_pages
        name: Setup Pages
        uses: actions/configure-pages@v5

      - id: upload_artifact
        name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./pages"

      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
